const ENTRIES1 = [
  {
    name: 'Beautiful and dramatic Antelope Canyon',
    description: 'Lorem ipsum dolor sit amet et nuncat mergitur',
    images: ['https://i.imgur.com/UYiroysl.jpg'],
    id: 'a1',
    category: 'test category',
    country: 'Test country',
    currency: '¥',
    prefecture: 'Tokyo',
    price: '1',
    publishDate: '2020-02-14T13:55:52.661Z',
    status: 'No Noticable Scratches or Dirt',
    userId: '5662484329398272',
    cancelled: false,
    cancelDate: null,
    lotteryUserIds: ['5734484288733184', '5758387459457024'],
    winnerUserId: null,
    currentCollectedPrice: null,
    available: true,
  },
  {
    name: 'Earlier this morning, NYC',
    images: ['https://i.imgur.com/UPrs1EWl.jpg'],
    description: 'Lorem ipsum dolor sit amet',
    id: 'a2',
    category: 'test category',
    country: 'Test country',
    currency: '¥',
    prefecture: 'Tokyo',
    price: '1',
    publishDate: '2020-02-14T13:55:52.661Z',
    status: 'No Noticable Scratches or Dirt',
    userId: '5662484329398272',
    cancelled: false,
    cancelDate: null,
    lotteryUserIds: ['5734484288733184', '5758387459457024'],
    winnerUserId: null,
    currentCollectedPrice: null,
    available: true,
  },
  {
    name: 'White Pocket Sunset',
    description: 'Lorem ipsum dolor sit amet et nuncat ',
    images: ['https://i.imgur.com/MABUbpDl.jpg'],
    id: 'a3',
    category: 'test category',
    country: 'Test country',
    currency: '¥',
    prefecture: 'Tokyo',
    price: '1',
    publishDate: '2020-02-14T13:55:52.661Z',
    status: 'No Noticable Scratches or Dirt',
    userId: '5662484329398272',
    cancelled: false,
    cancelDate: null,
    lotteryUserIds: ['5734484288733184', '5758387459457024'],
    winnerUserId: null,
    currentCollectedPrice: null,
    available: true,
  },
  {
    name: 'Acrocorinth, Greece',
    description: 'Lorem ipsum dolor sit amet et nuncat mergitur',
    images: ['https://i.imgur.com/KZsmUi2l.jpg'],
    id: 'a4',
    category: 'test category',
    country: 'Test country',
    currency: '¥',
    prefecture: 'Tokyo',
    price: '1',
    publishDate: '2020-02-14T13:55:52.661Z',
    status: 'No Noticable Scratches or Dirt',
    userId: '5662484329398272',
    cancelled: false,
    cancelDate: null,
    lotteryUserIds: ['5734484288733184', '5758387459457024'],
    winnerUserId: null,
    currentCollectedPrice: null,
    available: true,
  },
  {
    name: 'The lone tree, majestic landscape of New Zealand',
    description: 'Lorem ipsum dolor sit amet',
    images: ['https://i.imgur.com/2nCt3Sbl.jpg'],
    id: 'a5',
    category: 'test category',
    country: 'Test country',
    currency: '¥',
    prefecture: 'Tokyo',
    price: '1',
    publishDate: '2020-02-14T13:55:52.661Z',
    status: 'No Noticable Scratches or Dirt',
    userId: '5662484329398272',
    cancelled: false,
    cancelledDate: null,
    lotteryUserIds: ['5734484288733184', '5758387459457024'],
    winnerUserId: null,
    currentCollectedPrice: null,
    available: true,
  },
  {
    name: 'Middle Earth, Germany',
    description: 'Lorem ipsum dolor sit amet',
    images: ['https://i.imgur.com/lceHsT6l.jpg'],
    id: 'a6',
    category: 'test category',
    country: 'Test country',
    currency: '¥',
    prefecture: 'Tokyo',
    price: '1',
    publishDate: '2020-02-14T13:55:52.661Z',
    status: 'No Noticable Scratches or Dirt',
    userId: '5662484329398272',
    cancelled: false,
    cancelDate: null,
    lotteryUserIds: ['5734484288733184', '5758387459457024'],
    winnerUserId: null,
    currentCollectedPrice: null,
    available: true,
  },
  // {
  //   title: 'Favourites landscapes 1',
  //   subtitle: 'Lorem ipsum dolor sit amet',
  //   illustration: 'https://i.imgur.com/SsJmZ9jl.jpg',
  //   id: 'a7',
  // },
  // {
  //   title: 'Favourites landscapes 2',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
  //   illustration: 'https://i.imgur.com/5tj6S7Ol.jpg',
  //   id: 'a8',
  // },
  // {
  //   title: 'Favourites landscapes 3',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat',
  //   illustration: 'https://i.imgur.com/pmSqIFZl.jpg',
  //   id: 'a9',
  // },
  // {
  //   title: 'Favourites landscapes 4',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
  //   illustration: 'https://i.imgur.com/cA8zoGel.jpg',
  //   id: 'a10',
  // },
  // {
  //   title: 'Favourites landscapes 5',
  //   subtitle: 'Lorem ipsum dolor sit amet',
  //   illustration: 'https://i.imgur.com/pewusMzl.jpg',
  //   id: 'a11',
  // },
  // {
  //   title: 'Favourites landscapes 6',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat',
  //   illustration: 'https://i.imgur.com/l49aYS3l.jpg',
  //   id: 'a12',
  // },
  // {
  //   title: 'Favourites landscapes 1',
  //   subtitle: 'Lorem ipsum dolor sit amet',
  //   illustration: 'https://i.imgur.com/SsJmZ9jl.jpg',
  //   id: 'a13',
  // },
  // {
  //   title: 'Favourites landscapes 2',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
  //   illustration: 'https://i.imgur.com/5tj6S7Ol.jpg',
  //   id: 'a14',
  // },
  // {
  //   title: 'Favourites landscapes 3',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat',
  //   illustration: 'https://i.imgur.com/pmSqIFZl.jpg',
  //   id: 'a15',
  // },
  // {
  //   title: 'Favourites landscapes 4',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
  //   illustration: 'https://i.imgur.com/cA8zoGel.jpg',
  //   id: 'a16',
  // },
  // {
  //   title: 'Favourites landscapes 5',
  //   subtitle: 'Lorem ipsum dolor sit amet',
  //   illustration: 'https://i.imgur.com/pewusMzl.jpg',
  //   id: 'a17',
  // },
  // {
  //   title: 'Favourites landscapes 6',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat',
  //   illustration: 'https://i.imgur.com/l49aYS3l.jpg',
  //   id: 'a18',
  // },
  // {
  //   title: 'Favourites landscapes 1',
  //   subtitle: 'Lorem ipsum dolor sit amet',
  //   illustration: 'https://i.imgur.com/SsJmZ9jl.jpg',
  //   id: 'a19',
  // },
  // {
  //   title: 'Favourites landscapes 2',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
  //   illustration: 'https://i.imgur.com/5tj6S7Ol.jpg',
  //   id: 'a20',
  // },
  // {
  //   title: 'Favourites landscapes 3',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat',
  //   illustration: 'https://i.imgur.com/pmSqIFZl.jpg',
  //   id: 'a21',
  // },
  // {
  //   title: 'Favourites landscapes 4',
  //   subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
  //   illustration: 'https://i.imgur.com/cA8zoGel.jpg',
  //   id: 'a22',
  // },
  // {
  //   title: 'Favourites landscapes 5',
  //   subtitle: 'Lorem ipsum dolor sit amet',
  //   illustration: 'https://i.imgur.com/pewusMzl.jpg',
  //   id: '23a',
  // },
];

export {ENTRIES1};
