const countries = [
  // 'Afghanistan',
  // 'Albania',
  // 'Algeria',
  // 'Andorra',
  // 'Angola',
  // 'Anguilla',
  // 'Antigua Barbuda',
  // 'Argentina',
  // 'Armenia',
  // 'Aruba',
  // 'Australia',
  // 'Austria',
  // 'Azerbaijan',
  // 'Bahamas',
  // 'Bahrain',
  // 'Bangladesh',
  // 'Barbados',
  // 'Belarus',
  // 'Belgium',
  // 'Belize',
  // 'Benin',
  // 'Bermuda',
  // 'Bhutan',
  // 'Bolivia',
  // 'Bosnia Herzegovina',
  // 'Botswana',
  // 'Brazil',
  // 'British Virgin Islands',
  // 'Brunei',
  // 'Bulgaria',
  // 'Burkina Faso',
  // 'Burundi',
  // 'Cambodia',
  // 'Cameroon',
  // 'Cape Verde',
  // 'Cayman Islands',
  // 'Chad',
  // 'Chile',
  // 'China',
  // 'Colombia',
  // 'Congo',
  // 'Cook Islands',
  // 'Costa Rica',
  // 'Cote D Ivoire',
  // 'Croatia',
  // 'Cruise Ship',
  // 'Cuba',
  // 'Cyprus',
  // 'Czech Republic',
  // 'Denmark',
  // 'Djibouti',
  // 'Dominica',
  // 'Dominican Republic',
  // 'Ecuador',
  'Egypt',
  // 'El Salvador',
  // 'Equatorial Guinea',
  // 'Estonia',
  // 'Ethiopia',
  // 'Falkland Islands',
  // 'Faroe Islands',
  // 'Fiji',
  // 'Finland',
  // 'France',
  // 'French Polynesia',
  // 'French West Indies',
  // 'Gabon',
  // 'Gambia',
  // 'Georgia',
  // 'Germany',
  // 'Ghana',
  // 'Gibraltar',
  // 'Greece',
  // 'Greenland',
  // 'Grenada',
  // 'Guam',
  // 'Guatemala',
  // 'Guernsey',
  // 'Guinea',
  // 'Guinea Bissau',
  // 'Guyana',
  // 'Haiti',
  // 'Honduras',
  // 'Hong Kong',
  // 'Hungary',
  // 'Iceland',
  // 'India',
  // 'Indonesia',
  // 'Iran',
  // 'Iraq',
  // 'Ireland',
  // 'Isle of Man',
  // 'Israel',
  // 'Italy',
  // 'Jamaica',
  'Japan',
  // 'Jersey',
  // 'Jordan',
  // 'Kazakhstan',
  // 'Kenya',
  // 'Kuwait',
  // 'Kyrgyz Republic',
  // 'Laos',
  // 'Latvia',
  'Lebanon',
  // 'Lesotho',
  // 'Liberia',
  // 'Libya',
  // 'Liechtenstein',
  // 'Lithuania',
  // 'Luxembourg',
  // 'Macau',
  // 'Macedonia',
  // 'Madagascar',
  // 'Malawi',
  // 'Malaysia',
  // 'Maldives',
  // 'Mali',
  // 'Malta',
  // 'Mauritania',
  // 'Mauritius',
  // 'Mexico',
  // 'Moldova',
  // 'Monaco',
  // 'Mongolia',
  // 'Montenegro',
  // 'Montserrat',
  // 'Morocco',
  // 'Mozambique',
  // 'Namibia',
  // 'Nepal',
  // 'Netherlands',
  // 'Netherlands Antilles',
  // 'New Caledonia',
  // 'New Zealand',
  // 'Nicaragua',
  // 'Niger',
  // 'Nigeria',
  // 'Norway',
  // 'Oman',
  // 'Pakistan',
  // 'Palestine',
  // 'Panama',
  // 'Papua New Guinea',
  // 'Paraguay',
  // 'Peru',
  // 'Philippines',
  // 'Poland',
  // 'Portugal',
  // 'Puerto Rico',
  'Qatar',
  // 'Reunion',
  // 'Romania',
  'Russia',
  // 'Rwanda',
  // 'Saint Pierre Miquelon',
  // 'Samoa',
  // 'San Marino',
  // 'Satellite',
  // 'Saudi Arabia',
  // 'Senegal',
  // 'Serbia',
  // 'Seychelles',
  // 'Sierra Leone',
  // 'Singapore',
  // 'Slovakia',
  // 'Slovenia',
  // 'South Africa',
  // 'South Korea',
  // 'Spain',
  // 'Sri Lanka',
  // 'St Kitts Nevis',
  // 'St Lucia',
  // 'St Vincent',
  // 'St. Lucia',
  // 'Sudan',
  // 'Suriname',
  // 'Swaziland',
  // 'Sweden',
  // 'Switzerland',
  // 'Syria',
  // 'Taiwan',
  // 'Tajikistan',
  // 'Tanzania',
  // 'Thailand',
  // "Timor L'Este",
  // 'Togo',
  // 'Tonga',
  // 'Trinidad Tobago',
  // 'Tunisia',
  // 'Turkey',
  // 'Turkmenistan',
  // 'Turks Caicos',
  // 'Uganda',
  // 'Ukraine',
  'Dubai',
  // 'United Kingdom',
  // 'Uruguay',
  // 'Uzbekistan',
  // 'Venezuela',
  // 'Vietnam',
  // 'Virgin Islands (US)',
  // 'Yemen',
  // 'Zambia',
  // 'Zimbabwe',
].sort();

const perfectures = {
  Japan: [
    'Hokkaido',
    'Iwate',
    'Fukushima',
    'Nagano',
    'Niigata',
    'Akita',
    'Gifu',
    'Aomori',
    'Yamagata',
    'Kagoshima',
    'Hiroshima',
    'Hyogo',
    'Shizuoka',
    'Miyazaki',
    'Kumamoto',
    'Miyagi',
    'Okayama',
    'Kochi',
    'Shimane',
    'Tochigi',
    'Gumma',
    'Oita',
    'Yamaguchi',
    'Ibaraki',
    'Mie',
    'Ehime',
    'Aichi',
    'Chiba',
    'Fukuoka',
    'Wakayama',
    'Kyoto',
    'Yamanashi',
    'Toyama',
    'Fukui',
    'Ishikawa',
    'Tokushima',
    'Nagasaki',
    'Shiga',
    'Saitama',
    'Nara',
    'Tottori',
    'Saga',
    'Kanagawa',
    'Okinawa',
    'Tokyo',
    'Osaka',
    'Kagawa',
  ].sort(),
  Lebanon: [
    'Akkar',
    'Baalbek',
    'Hermel',
    'Beirut',
    'Rashaya',
    'Western Beqaa',
    'Zahle',
    'Aley',
    'Baabda',
    'Chouf',
    'Jbeil',
    'Keserwan',
    'Matn',
    'Bint Jbeil',
    'Hasbaya',
    'Marjeyoun',
    'Nabatieh',
    'Batroun',
    'Bsharri',
    'Koura',
    'Miniyeh-Danniyeh',
    'Tripoli',
    'Zgharta',
    'Sidon',
    'Jezzine',
    'Tyre',
  ].sort(),
  Egypt: [
    'Alexandria',
    'Aswan',
    'Asyut',
    'Beheira',
    'Beni Suef',
    'Cairo',
    'Dakahlia',
    'Damietta',
    'Faiyum',
    'Gharbia',
    'Giza',
    'Ismailia',
    'Kafr El Sheikh',
    'Luxor',
    'Matruh',
    'Minya',
    'Monufia',
    'New Valley',
    'North Sinai',
    'Port Said',
    'Qalyubia',
    'Qena',
    'Red Sea',
    'Sharqia',
    'Sohag',
    'South Sinai',
    'Suez',
  ].sort(),
  Russia: [
    'Amur',
    'Arkhangelsk',
    'Astrakhan',
    'Belgorod',
    'Bryansk',
    'Chelyabinsk',
    'Irkutsk',
    'Ivanovo',
    'Kaliningrad',
    'Kaluga',
    'Kemerovo',
    'Kirov',
    'Kostroma',
    'Kurgan',
    'Kursk',
    'Leningrad',
    'Lipetsk',
    'Magadan',
    'Moscow',
    'Murmansk',
    'Nizhny',
    'Novgorod',
    'Novgorod',
    'Novosibirsk',
    'Omsk',
    'Orenburg',
    'Oryol',
    'Penza',
    'Pskov',
    'Rostov',
    'Ryazan',
    'Sakhalin',
    'Samara',
    'Saratov',
    'Smolensk',
    'Sverdlovsk',
    'Tambov',
    'Tomsk',
    'Tula',
    'Tver',
    'Tyumen',
    'Ulyanovsk',
    'Vladimir',
    'Volgograd',
    'Vologda',
    'Voronezh',
    'Yaroslavl',
  ].sort(),
  Qatar: [
    'Abu Dhalouf',
    'Abu Hamour',
    'Abu Samra',
    'Ad Dawhah al Jadidah',
    'Ain Khaled',
    'Ain Sinan',
    'Al Aziziya',
    'Al Bidda',
    'Al Daayen',
    'Al Dafna',
    'Al Ebb',
    'Al Egla',
    'Al Gharrafa',
    'Al Ghuwariyah',
    'Al Hilal',
    'Al Jasrah',
    'Al Jeryan',
    'Al Karaana',
    'Al Kharaitiyat',
    'Al Kharayej',
    'Al Kharrara',
    'Al Kheesa',
    'Al Khor',
    'Al Khulaifat',
    'Al Luqta',
    'Al Mamoura',
    'Al Mansoura',
    'Al Markhiyah',
    'Al Mashaf',
    'Al Masrouhiya',
    'Al Mearad',
    'Al Messila',
    'Al Mirqab',
    'Al Najada',
    'Al Nasraniya',
    'Al Qassar',
    'Al Rufaa',
    'Al Sadd',
    'Al Sailiya',
    'Al Sakhama',
    'Al Seej',
    'Al Shagub',
    'Al Souq',
    'Al Tarfa',
    'Al Thakhira',
    'Al Themaid',
    'Al Thumama',
    'Al Thumama',
    'Al Utouriya',
    'Al Waab',
    'Al Wajba',
    'Al Wakrah',
    'Al Wukair',
    'Al Zubarah',
    'Al-Shahaniya',
    "Ar Ru'ays",
    'As Salatah',
    'Baaya',
    'Bani Hajer',
    'Barahat Al Jufairi',
    'Bu Fasseela',
    'Bu Samra',
    'Bu Sidra',
    'Dahl Al Hamam',
    'Doha International Airport',
    'Doha Port',
    'Duhail',
    'Dukhan',
    'Fereej Abdel Aziz',
    'Fereej Al Amir',
    'Fereej Al Asiri',
    'Fereej Al Asmakh',
    'Fereej Al Manaseer',
    'Fereej Al Murra',
    'Fereej Al Nasr',
    'Fereej Al Soudan',
    'Fereej Al Zaeem',
    'Fereej Bin Durham',
    'Fereej Bin Mahmoud',
    'Fereej Bin Omran',
    'Fereej Kulaib',
    'Fereej Mohammed Bin Jassim',
    'Fuwayrit',
    'Gharrafat Al Rayyan',
    'Hamad Medical City',
    'Hazm Al Markhiya',
    'Industrial Area',
    'Izghawa',
    'Izghawa',
    'Jabal Thuaileb',
    'Jelaiah',
    'Jeryan Jenaihat',
    'Jeryan Nejaima',
    'Khawr al Udayd',
    'Leabaib',
    'Lebday',
    'Lejbailat',
    'Lekhwair',
    'Leqtaifiya',
    'Lijmiliya',
    'Luaib',
    'Lusail',
    'Madinat Al Kaaban',
    'Madinat ash Shamal',
    'Madinat Khalifa North',
    'Madinat Khalifa South',
    'Mebaireek',
    'Mehairja',
    'Mesaieed',
    'Mesaieed Industrial Area',
    'Mesaimeer',
    'Muaither',
    'Muraikh',
    'Mushayrib',
    'Najma',
    'New Al Hitmi',
    'New Al Mirqab',
    'New Al Rayyan',
    'New Fereej Al Ghanim',
    'New Fereej Al Khulaifat',
    'New Salata',
    'Nuayjah',
    'Old Airport',
    'Old Al Ghanim',
    'Old Al Hitmi',
    'Old Al Rayyan',
    'Onaiza',
    'Ras Abu Aboud',
    'Ras Lafan',
    'Rawdat Al Hamama',
    'Rawdat Al Khail',
    'Rawdat Egdaim',
    'Rawdat Rashed',
    'Rumeilah',
    'Sawda Natheel',
    'Shagra',
    'Simaisma',
    'The Pearl',
    'Umm Bab',
    'Umm Birka',
    'Umm Ghuwailina',
    'Umm Lekhba',
    'Umm Qarn',
    'Umm Salal Ali',
    'Umm Salal Mohammed',
    'Wadi Al Banat',
    'Wadi Al Sail',
    'Wadi Al Wasaah',
    'Wadi Lusail',
  ].sort(),
  'Abu Dhabi': [].sort(),
  Dubai: [
    'Hatta',
    'The World',
    'Palm Jebel Ali',
    'Palm Jumeirah',
    'Palm Deira',
    'Jebel Ali Village',
    'Jebel Ali Free Zone',
    'Jebel Ali Industrial Area',
    'Jebel Ali Port',
    'Jebel Ali Gardens',
    'Green Community',
    'Dubai Investments Park',
    'Discovery Gardens',
    'Jumeirah Lake Towers',
    'Jumeirah Beach Residence',
    'Dubai Marina',
    'Jumeirah Islands',
    'Emirates Hills',
    'The Springs',
    'The Meadows',
    'The Greens',
    'Al Barsha',
    'Al Sufouh',
    'Dubai Internet City',
    'Dubai Media City',
    'Knowledge Village',
    'Madinat Jumeirah',
    'Umm Suqiem',
    'Umm Al Sheif',
    'Al Safa',
    'Al Wasl',
    'Jumeirah 3',
    'Jumeirah 2',
    'Jumeirah 1',
    'Dubai Design District',
    'Nad Al Sheba',
    'Business Bay',
    'Old Town Dubai',
    'Downtown Dubai',
    'Dubai International Financial Center',
    'Al Quoz',
    'Oud Metha',
    'Dubai Healthcare City',
    'Al Jafiliya',
    'Zabeel',
    'Karama',
    'Al Mankhool',
    'Hor Al Anz',
    'Al Ras',
    'Al Sabkha',
    'Deira Fish Market',
    'Hyatt',
    'Al Murar',
    'Al Baraha',
    'Abu Hail',
    'Al Waheda',
    'Al Mamzar',
    'Dubai Airport Free Zone',
    'Dubai Airport',
    'Al Ghusais',
    'Al Garhood',
    'Dubai Festival City',
    'Mirdif',
    'Rashidiya',
    'Al Warqa',
    'International City',
    'Dubai Academic City',
    'Dubai Silicon Oasis',
  ].sort(),
};

const perfecturesList = {
  Japan: 'Tokyo',
  Lebanon: 'Beirut',
  Egypt: 'Cairo',
  Russia: 'Moscow',
  Qatar: 'Shagra',
  Dubai: 'Dubai Internet City',
};

const countryCodeList = {
  JP: 'Japan',
  LB: 'Lebanon',
};

const currencies = {
  Japan: '¥(JPY)',
  Lebanon: 'LBP',
  Egypt: 'EGP',
  Russia: '₽(RUB)',
  Qatar: 'QAR',
  Dubai: 'AED',
};

export {countries, perfectures, perfecturesList, countryCodeList, currencies};
