let lotteryItemCategories = {
  en: [
    'Warehouse Deals',
    'Industrial & Scientific',
    'Gift Cards',
    'Credit Cards',
    'Large Appliances',
    'DIY, Tools & Garden',
    'Car & Bike Products',
    'Sports',
    'Musical Instruments',
    'Hobby',
    'Toys',
    'Jewelry',
    'Wrist Watches',
    'Shoes & Bags',
    'Clothing & Accessories',
    "Women's Fashion",
    "Kids and Baby's Fashion",
    'Baby & Maternity',
    'Food & Beverage',
    'Beauty',
    'Health & Personal Care',
    'Pet Supplies',
    'Kitchen & Housewares',
    'Stationery and Office Products',
    'Electronics & Cameras',
    'Computers & Accessories',
    'Software',
    'Computer & Video Games',
    'Movies & TV',
    'Classical',
    'Music',
    'English Books',
    'Japanese Books',
    'Apps & Games',
    'Digital Music',
    'LIFE',
    'Audible Audiobooks',
    'Antique',
    'Art',
    'Tickets & Vouchers',
    'Jobs',
    'Real Estate',
    'Properties',
    'Appartments',
    'Private Lessons',
    'Spa',
    'Books & Magazines',
    'Vehicles',
  ].sort(),
  jp: [
    '倉庫取引',
    'インダストリアル＆サイエンティフィック',
    'ギフトカード',
    'クレジットカード',
    '大型家電',
    'DIY、ツール＆ガーデン',
    'カー＆バイク製品',
    'スポーツ',
    '楽器',
    '趣味',
    'おもちゃ',
    'ジュエリー',
    '腕時計',
    '靴とバッグ',
    '衣料品＆アクセサリー',
    'レディースファッション',
    'キッズ＆ベイビーファッション',
    'ベビー＆マタニティ',
    '食料と飲料',
    '美しさ',
    'ヘルス＆パーソナルケア',
    'ペット用品',
    'キッチン＆家庭用品',
    '文房具・事務用品',
    'エレクトロニクス＆カメラ',
    'コンピュータとアクセサリ',
    'ソフトウェア',
    'コンピュータ＆ビデオゲーム',
    '映画＆テレビ',
    'クラシック',
    '音楽',
    '英語の本',
    '日本の本',
    'アプリとゲーム',
    'デジタルミュージック',
    '生活',
    '可聴オーディオブック',
    'アンティーク',
    '美術',
    'チケットとバウチャー',
    '仕事',
    '不動産',
    'プロパティ',
    'アパート',
    'プライベートレッスン',
    'スパ',
    '本と雑誌',
    '車両',
  ].sort(),
};

lotteryItemCategories.en = [
  ...lotteryItemCategories.en.map(item => ({value: item})),
  {value: 'Other'},
];

lotteryItemCategories.jp = [
  ...lotteryItemCategories.jp.map(item => ({value: item})),
  {value: '他の'},
];

const lotteryItemTypes = {
  'Home Appliances': [],
  Computer: [
    'Computer',
    'Tablet',
    'Smart Phones',
    'Ebook Reader',
    'Digital Camera',
    'Peripheral Equipment',
    'Software',
    'Supply',
    'Parts',
    'Server',
    'Work Station',
    'PDA',
    'Pocket Computer',
    'Other',
  ],
  Music: [],
  'Books & Magazines': [],
  'Movies & Videos': [],
  'Teacher Lessons': [],
  'Real Estate': [],
  Vehicles: [],
  Pets: [],
  Jobs: [],
  'Kids & Babies': [],
  'Beauty & Healthcare': [],
  'Tickets & Vouchers': [],
  'Office Supplies': [],
  Gardening: [],
  'Fashion & Clothing': [],
  'Toys & Games': [],
  Antique: [],
  Art: [],
  Sports: [],
};

const mimeTypes = {
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
};

const lotteryItemConditions = {
  en: [
    'New',
    'Used',
    'Nearly Used',
    'No Noticable Scratches or Dirt',
    'Some Scratches & Dirt',
    'Overall Bad Condition',
    'Excellent',
    'Good',
    'Great',
  ]
    .sort()
    .map(item => ({value: item})),
  jp: [
    '新しい',
    '中古',
    'ほぼ使用済み',
    '目立った傷や汚れはありません',
    'いくつかの傷と汚れ',
    '全体的に悪い状態',
    '優秀な',
    '良い',
    '素晴らしい',
  ]
    .sort()
    .map(item => ({value: item})),
};

export {
  lotteryItemCategories,
  lotteryItemConditions,
  mimeTypes,
  lotteryItemTypes,
};
